# Generated by Django 3.1.3 on 2023-05-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='coop',
        ),
    ]
