# Generated by Django 4.1.7 on 2023-05-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_auto_20230524_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coopanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
